### PR TITLE
Fix mod.conf issues

### LINKED ISSUE #1: Dependencies issues
Currently, there's a empty `depends.txt`. This should be deleted, plus, it is deprecated.
`description.txt` should be also deleted.

Also, `mod.conf` has `optional_depends` and `depends`. This is not needed as there are no (soft) dependencies in this mod.

### PR DESCRIPTION
**Pull request by Panquesito7**
Fixes some dependencies issues.
Closes #1.

### CODE REVIEW

**Comment by sofar** [comment]
The commit title should be relevant. Please change it to something meaningful.

**Comment by Panquesito7** [comment]
> Please change it

Is it ok now? 🙂

**Comment by sofar** [comment]
Changing the title in github doesn't work. You need to `amend` the git commit and then `force push` it to update the git commit.

**Comment by Panquesito7** [comment]
Will do.

**Comment by Panquesito7** [comment]
Fixed.

**Pull request merged**
